---

- name: Download terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/0.12.13/terraform_0.12.13_linux_amd64.zip 
    dest: /opt/bin
    creates: /opt/bin/terraform
    remote_src: yes
  become_user: kevinchou


- name: Download Packer
  unarchive:
    src: https://releases.hashicorp.com/packer/1.4.5/packer_1.4.5_linux_amd64.zip
    dest: /opt/bin
    creates: /opt/bin/packer
    remote_src: yes
  become_user: kevinchou

- name: install key (apt)
  become: yes
  apt_key:
    url: 'https://packages.microsoft.com/keys/microsoft.asc'
    state: present

- name: install VS Code repo (apt)
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    filename: vscode
    state: present

- name: install VS Code (apt)
  become: yes
  apt:
    name: code
    state: present
    update_cache: yes

- name: Download golang
  unarchive:
    src: https://dl.google.com/go/go1.13.4.linux-amd64.tar.gz
    dest: /opt/
    remote_src: yes
    creates: "/opt/go/"

- name: Install aws-cli
  pip:
    name: awscli
    executable: pip3