---

- name: Install oh-my-zsh
  command: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

- name: Add source to zsh_profile
  lineinfile:
    path: ~/.zshrc
    line: source ~/.zsh_profile

- name: export golang environtment variable
  blockinfile:
    path: ~/.zsh_profile
    block: | 
      export GOROOT=/opt/go
      export GOPATH=$HOME/Development/GOLANG
      export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
      export PATH="$PATH:/opt/bin"